// src/launcher/Launcher.tsx
// The Launcher: the universal entry point to every Action, and only that.
// Picking is keyboard only — it is summoned by a hotkey, so the hands are
// already on the keys — and the window dies with its focus. Authoring an Action
// lives in Settings (ADR-0003), a window that can survive a click elsewhere; a
// form inside a picker cannot.
//
// The window is the query, the ranked list and the keys. One row is
// `ActionRow`; the registry behind it is `actions.ts`.
import * as React from "react";
import { SearchIcon, SlidersHorizontalIcon } from "lucide-react";
import { BrandMark } from "@/components/BrandMark";
import { Kbd } from "@/components/Kbd";
import { Button } from "@/components/ui/button";
import { rank } from "@/lib/fuzzy";
import {
  hideLauncher,
  onActionsChanged,
  onLauncherOpened,
  pickAction,
  showSettings,
  Subscriptions,
} from "@/lib/ipc";
import { useStore } from "@/lib/useStore";
import { ActionRow, BrokenRow } from "./ActionRow";
import { actionStore } from "./actions";

export function Launcher() {
  const store = useStore(actionStore);
  const [query, setQuery] = React.useState("");
  const [wanted, setWanted] = React.useState(0);
  const [selectionChars, setSelectionChars] = React.useState(0);

  const input = React.useRef<HTMLInputElement | null>(null);
  const active = React.useRef<HTMLLIElement | null>(null);

  const snapshot = store.snapshot;
  const matches = React.useMemo(
    () => rank(snapshot.actions, query, (action) => [action.name, action.description ?? ""]),
    [snapshot.actions, query],
  );

  // Clamped rather than reset: the list re-ranks on every keystroke, and a
  // selection that survives the narrowing is what makes typing-then-Enter work.
  const selected = matches.length === 0 ? 0 : Math.min(wanted, matches.length - 1);

  const focusQuery = React.useCallback(() => {
    input.current?.focus();
    input.current?.select();
  }, []);

  React.useEffect(() => {
    void actionStore.refresh();
    focusQuery();

    const subscriptions = new Subscriptions();
    subscriptions.add(onActionsChanged((next) => actionStore.adoptActions(next))).add(
      onLauncherOpened((chars) => {
        // A fresh summon starts from a clean slate: the window is reused
        // (ADR-0007), so the last visit's query is still sitting in it.
        setSelectionChars(chars);
        setQuery("");
        setWanted(0);
        focusQuery();
      }),
    );
    return () => void subscriptions.dispose();
  }, [focusQuery]);

  // Arrowing past the fold has to bring the row with it. Scrolling the *row*
  // rather than computing an offset keeps this correct whatever the row height
  // and whether or not the description line is there.
  React.useEffect(() => {
    active.current?.scrollIntoView({ block: "nearest" });
  }, [selected]);

  /** Editing is elsewhere. `show_settings` hides this window itself — doing it
   *  from here first would let the foreground go back to the app underneath,
   *  and Settings would open behind it. */
  const openSettings = () => void showSettings();

  const run = (index: number) => {
    const action = matches[index];
    if (action) void pickAction(action.id);
  };

  // On the window, not on the card: clicking a row leaves focus on the body,
  // and a handler bound to the tree would stop answering Escape the moment the
  // mouse was used once.
  React.useEffect(() => {
    const move = (delta: number) => {
      if (matches.length === 0) return;
      setWanted((selected + delta + matches.length) % matches.length);
    };

    const onKeyDown = (event: KeyboardEvent) => {
      switch (event.key) {
        case "Escape":
          event.preventDefault();
          void hideLauncher();
          return;
        case "ArrowDown":
          event.preventDefault();
          move(1);
          return;
        case "ArrowUp":
          event.preventDefault();
          move(-1);
          return;
        case "Enter":
          event.preventDefault();
          if (matches[selected]) void pickAction(matches[selected].id);
          return;
        case "Tab":
          // Focus never leaves the query box, so Tab is just another arrow.
          event.preventDefault();
          move(event.shiftKey ? -1 : 1);
          return;
        case ",":
          if (event.ctrlKey) {
            event.preventDefault();
            void showSettings();
          }
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [matches, selected]);

  const nothing = matches.length === 0 && snapshot.errors.length === 0;

  return (
    // The frameless card: it fills the window rect exactly, so the drop shadow
    // under it is DWM's rather than one painted here. The radius matches the
    // ~8px Windows 11 rounds an undecorated window at — a larger one is clipped
    // by DWM's and shows as a nick in each corner.
    <div className="bg-background flex h-screen flex-col overflow-hidden rounded-lg border">
      <div className="flex h-14 flex-none items-center gap-3 border-b px-4">
        <SearchIcon className="text-muted-quiet size-4.5 flex-none" />
        <input
          ref={input}
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search Actions…"
          spellCheck={false}
          autoComplete="off"
          aria-label="Search Actions"
          className="placeholder:text-muted-foreground min-w-0 flex-1 bg-transparent text-query outline-none"
        />
        <Kbd>Esc</Kbd>
      </div>

      <ul
        role="listbox"
        aria-label="Actions"
        className="min-h-0 flex-1 list-none overflow-y-auto p-0 scrollbar-gutter-stable"
      >
        {snapshot.errors.map((error) => (
          <BrokenRow
            key={error.file_name}
            file={error.file_name}
            message={error.message}
            onOpen={openSettings}
          />
        ))}

        {matches.map((action, index) => (
          <ActionRow
            key={action.id}
            ref={index === selected ? active : undefined}
            action={action}
            conflict={snapshot.hotkey_errors[action.id]}
            query={query}
            selected={index === selected}
            onSelect={() => setWanted(index)}
            onRun={() => run(index)}
          />
        ))}

        {/* Centred in what is left of the window rather than parked under the
            query box: the list is the window's whole body, so an empty one that
            hugs the top leaves a void that reads as content failing to load. */}
        {nothing ? (
          <li className="flex h-full flex-col items-center justify-center gap-3 px-4 text-center">
            {snapshot.actions.length === 0 ? (
              <>
                <BrandMark className="text-brand size-6" />
                <p className="text-muted-foreground text-quiet">No Actions yet.</p>
                <Button size="sm" onClick={openSettings}>
                  <SlidersHorizontalIcon /> Add one in Settings
                </Button>
              </>
            ) : (
              <>
                <p className="text-muted-foreground text-quiet">
                  Nothing matches{" "}
                  <code className="bg-muted text-foreground rounded px-1 font-mono">{query}</code>.
                </p>
                <p className="text-muted-quiet text-note">Backspace to widen the search.</p>
              </>
            )}
          </li>
        ) : null}
      </ul>

      {/* The Selection count is the one thing this window knows that the list
          cannot show, and the keys are worth the space because the window is
          keyboard-first. The legend goes when there is nothing to move through. */}
      <div className="text-muted-quiet flex h-8 flex-none items-center gap-3 border-t pr-1 pl-4 text-meta">
        <span className="flex-1 truncate">
          {selectionChars > 0 ? `${selectionChars} characters selected` : "No selection"}
        </span>
        {matches.length > 0 ? (
          <span className="flex flex-none items-center gap-1" aria-hidden="true">
            <Kbd>↑</Kbd>
            <Kbd>↓</Kbd> move <Kbd>↵</Kbd> run
          </span>
        ) : null}
        <Button
          variant="ghost"
          size="icon-sm"
          title="Settings (Ctrl+,)"
          aria-label="Settings"
          onClick={openSettings}
        >
          <SlidersHorizontalIcon className="size-3.5" />
        </Button>
      </div>
    </div>
  );
}

// src/launcher/Launcher.svelte
<script lang="ts">
  // The Launcher: the universal entry point to every Action, and only that.
  // Picking is keyboard only — it is summoned by a hotkey, so the hands are
  // already on the keys — and the window dies with its focus. Authoring an
  // Action lives in Settings (ADR-0003), a window that can survive a click
  // elsewhere; a form inside a picker cannot.
  //
  // This file is the window: the query, the selection, and the keys that belong
  // to the window rather than to the field. The list is `ActionList`.
  import { onMount } from "svelte";
  import {
    hideLauncher,
    onActionsChanged,
    onLauncherOpened,
    pickAction,
    showSettings,
    Subscriptions,
  } from "../lib/ipc";
  import { rank } from "../lib/fuzzy";
  import type { Action } from "../lib/types";
  import ActionList from "./ActionList.svelte";
  import { actions } from "./actions.svelte";

  let query = $state("");
  let selected = $state(0);
  let selectionChars = $state(0);
  let list = $state<ActionList | null>(null);

  const matches = $derived(
    rank(actions.snapshot.actions, query, (action) => [action.name, action.description ?? ""]),
  );

  // Clamp rather than reset: the list re-ranks on every keystroke.
  $effect(() => {
    if (selected >= matches.length) selected = Math.max(0, matches.length - 1);
  });

  const subscriptions = new Subscriptions();

  onMount(() => {
    void actions.refresh();
    subscriptions.add(onActionsChanged((next) => actions.adoptActions(next))).add(
      onLauncherOpened((chars) => {
        // A fresh summon starts from a clean slate: the window is reused
        // (ADR-0007), so the last visit's query is still sitting in it.
        selectionChars = chars;
        query = "";
        selected = 0;
        list?.focusQuery();
      }),
    );
    list?.focusQuery();
    return () => void subscriptions.dispose();
  });

  function move(delta: number) {
    if (matches.length === 0) return;
    selected = (selected + delta + matches.length) % matches.length;
    list?.scrollSelectedIntoView();
  }

  function run(action: Action | undefined) {
    if (!action) return;
    void pickAction(action.id);
  }

  /** Editing is elsewhere. `show_settings` hides this window itself — doing it
   *  from here first would let the foreground go back to the app underneath,
   *  and Settings would open behind it. */
  function openSettings() {
    void showSettings();
  }

  function onKeydown(event: KeyboardEvent) {
    switch (event.key) {
      case "Escape":
        event.preventDefault();
        void hideLauncher();
        return;
      case "ArrowDown":
        event.preventDefault();
        move(1);
        return;
      case "ArrowUp":
        event.preventDefault();
        move(-1);
        return;
      case "Enter":
        event.preventDefault();
        run(matches[selected]);
        return;
      case "Tab":
        // Focus never leaves the query box, so Tab is just another arrow.
        event.preventDefault();
        move(event.shiftKey ? -1 : 1);
        return;
      case ",":
        if (event.ctrlKey) {
          event.preventDefault();
          openSettings();
        }
    }
  }
</script>

<svelte:window on:keydown={onKeydown} />

<div class="surface">
  <ActionList
    bind:this={list}
    {matches}
    bind:query
    bind:selected
    {selectionChars}
    onrun={run}
    onsettings={openSettings}
  />
</div>
