// src/settings/sections/actions/RawFileEditor.tsx
// A file that fails to parse is never dropped (ADR-0003) — it is reported and
// stays editable as text, which is the only way back from a bad hand-edit.
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Callout } from "@/components/Callout";
import { useStore } from "@/lib/useStore";
import { actionStore } from "../../actions";

export function RawFileEditor() {
  const store = useStore(actionStore);
  const raw = store.raw;
  if (!raw) return null;

  const parseError = store.snapshot.errors.find((error) => error.file_name === raw.file)?.message;

  return (
    <>
      {parseError ? (
        <Callout tone="danger">
          <p>{parseError}</p>
        </Callout>
      ) : null}

      <Textarea
        className="font-mono min-h-55 text-xs"
        spellCheck={false}
        value={raw.text}
        onChange={(event) => store.editRaw(event.currentTarget.value)}
      />

      {raw.error ? <p className="text-destructive font-small mt-1 text-xs">{raw.error}</p> : null}

      <div className="mt-3 flex items-center gap-2">
        <Button onClick={() => void store.saveRaw()}>Save file</Button>
        <span className="text-muted-foreground font-small text-xs">
          It reloads the moment it parses.
        </span>
      </div>
    </>
  );
}

// src/settings/sections/actions/RawFileEditor.svelte
<script lang="ts">
  // A file that fails to parse is never dropped (ADR-0003) — it is reported and
  // stays editable as text, which is the only way back from a bad hand-edit.
  import Callout from "../../../lib/ui/Callout.svelte";
  import { actionStore } from "../../actions.svelte";

  const raw = $derived(actionStore.raw);
  const parseError = $derived(
    actionStore.snapshot.errors.find((error) => error.file_name === raw?.file)?.message,
  );
</script>

{#if raw}
  {#if parseError}
    <Callout tone="danger"><p>{parseError}</p></Callout>
  {/if}

  <textarea class="raw" bind:value={actionStore.raw!.text} spellcheck="false"></textarea>

  {#if raw.error}
    <p class="hint error">{raw.error}</p>
  {/if}

  <div class="row">
    <button class="primary" onclick={() => actionStore.saveRaw()}>Save file</button>
    <span class="hint">It reloads the moment it parses.</span>
  </div>
{/if}

<style>
  .raw {
    min-height: 220px;
    font-family: var(--font-mono);
    font-size: var(--text-sm);
  }

  .row {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    margin-top: var(--space-3);
  }
</style>
