// src/lib/ui/Segmented.svelte
<script lang="ts" generics="T extends string">
  // Three-or-so mutually exclusive choices, shown rather than hidden behind a
  // dropdown. A real radiogroup with roving tabindex: one tab stop, arrows
  // move within it.
  interface Option {
    value: T;
    label: string;
  }

  interface Props {
    value: T;
    options: Option[];
    label: string;
    id?: string;
    describedBy?: string;
    onchange: (value: T) => void;
  }

  let { value, options, label, id, describedBy, onchange }: Props = $props();

  function onKeydown(event: KeyboardEvent) {
    const step = event.key === "ArrowRight" || event.key === "ArrowDown" ? 1 :
                 event.key === "ArrowLeft" || event.key === "ArrowUp" ? -1 : 0;
    if (step === 0) return;
    event.preventDefault();
    const at = options.findIndex((option) => option.value === value);
    const next = options[(at + step + options.length) % options.length];
    onchange(next.value);
  }
</script>

<!-- The group itself is deliberately not focusable: with roving tabindex the
     checked radio is the tab stop, which is what ARIA's radiogroup pattern
     asks for. A tabindex here would add a second, useless stop. -->
<!-- svelte-ignore a11y_interactive_supports_focus -->
<div
  class="segmented"
  role="radiogroup"
  aria-label={label}
  aria-describedby={describedBy}
  {id}
  onkeydown={onKeydown}
>
  {#each options as option (option.value)}
    <button
      type="button"
      role="radio"
      aria-checked={option.value === value}
      tabindex={option.value === value ? 0 : -1}
      class:active={option.value === value}
      onclick={() => onchange(option.value)}
    >
      {option.label}
    </button>
  {/each}
</div>

<style>
  .segmented {
    display: inline-flex;
    gap: 2px;
    padding: 2px;
    border: 1px solid var(--border-strong);
    border-radius: var(--radius-md);
    background: var(--bg-sunken);
    align-self: flex-start;
  }

  button {
    border: none;
    background: none;
    border-radius: var(--radius-sm);
    padding: var(--space-1) var(--space-3);
    color: var(--text-dim);
    font-size: var(--text-sm);
  }

  button:hover:not(:disabled) {
    background: var(--bg-hover);
    border-color: transparent;
    color: var(--text);
  }

  button.active {
    background: var(--bg-raised);
    color: var(--text);
    font-weight: var(--weight-medium);
    box-shadow: var(--shadow-sm);
  }
</style>

// src/components/Segmented.tsx
// Three-or-so mutually exclusive choices, shown rather than hidden behind a
// dropdown. shadcn/ui's ToggleGroup in `single` mode is Radix's roving-focus
// group, which is the same one-tab-stop-plus-arrows behaviour the hand-rolled
// radiogroup implemented.
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";

interface SegmentedProps<T extends string> {
  value: T;
  options: { value: T; label: string }[];
  label: string;
  id?: string;
  describedBy?: string;
  onChange: (value: T) => void;
}

export function Segmented<T extends string>({
  value,
  options,
  label,
  id,
  describedBy,
  onChange,
}: SegmentedProps<T>) {
  return (
    <ToggleGroup
      type="single"
      id={id}
      aria-label={label}
      aria-describedby={describedBy}
      value={value}
      // Radix clears a single-value group when its active item is pressed
      // again. There is no "no Input Source", so an empty value is dropped
      // rather than written.
      onValueChange={(next) => next && onChange(next as T)}
      size="sm"
      className="bg-muted self-start gap-0.5 rounded-md border p-0.5"
    >
      {options.map((option) => (
        <ToggleGroupItem
          key={option.value}
          value={option.value}
          // Selected is the inverted chip, and it is the only fill on the pane —
          // 17:1 against its own label, and nothing else here is filled, so it
          // cannot be mistaken for anything. That also settles what the stock
          // variant gets wrong: it gives the selected item and the hovered one
          // the same `bg-accent`, and `--accent` equals `--muted`, so a hover
          // fill would be indistinguishable from the group's own ground. The
          // fill means "selected" and nothing else; hover brightens the label.
          className="text-muted-foreground data-[state=off]:hover:bg-transparent data-[state=off]:hover:text-foreground data-[state=on]:bg-primary data-[state=on]:text-primary-foreground data-[state=on]:font-medium rounded-sm px-3 transition-colors duration-150 ease-out motion-reduce:transition-none"
        >
          {option.label}
        </ToggleGroupItem>
      ))}
    </ToggleGroup>
  );
}
