// src/settings/SettingsNav.svelte
<script lang="ts">
  // One entry per section, Actions included — a single "Actions" item, not one
  // per file: the list belongs in the pane, where a row has room for its
  // Input Source and its hotkey. A nav column of Actions would make "pick a
  // section" and "pick an Action" the same gesture for two unlike things.
  import { BrandMark, Folder, Keyboard, ListIcon, Palette, Plug, Sliders } from "../lib/icons";
  import { revealConfigDir } from "../lib/ipc";
  import { actionStore } from "./actions.svelte";
  import { settings, type SectionRoute } from "./store.svelte";

  const SECTIONS: { id: SectionRoute; label: string; icon: typeof Plug }[] = [
    { id: "connection", label: "Connection", icon: Plug },
    { id: "actions", label: "Actions", icon: ListIcon },
    { id: "triggering", label: "Triggering", icon: Keyboard },
    { id: "appearance", label: "Appearance", icon: Palette },
    { id: "defaults", label: "Model defaults", icon: Sliders },
  ];

  const route = $derived(settings.route);

  /** A section is flagged when something inside it needs attention, so a
   *  problem in a pane you are not looking at is still discoverable. A degraded
   *  model list is amber, not red: the dropdown still works. */
  const sectionFlag = $derived.by(
    (): Record<SectionRoute, "bad" | "warn" | null> => ({
      connection:
        settings.keyStatus?.kind === "read-error" || settings.test.state === "failed"
          ? "bad"
          : settings.keyStatus?.kind === "no-credential"
            ? "warn"
            : null,
      // A file that does not parse, or a Direct Hotkey that lost its conflict:
      // both are only repairable from inside this section.
      actions: actionStore.flagged ? "bad" : null,
      triggering: settings.startupErrors.length > 0 ? "bad" : null,
      appearance: null,
      defaults: settings.models !== null && !settings.models.live ? "warn" : null,
    }),
  );
</script>

<nav aria-label="Settings">
  <div class="brand">
    <BrandMark size={20} />
    <span>Beckon</span>
  </div>

  <ul class="sections">
    {#each SECTIONS as section (section.id)}
      {@const Icon = section.icon}
      {@const active = route === section.id}
      <li>
        <button
          class="nav-item"
          class:active
          aria-current={active ? "page" : undefined}
          onclick={() => settings.go(section.id)}
        >
          <span class="rail"></span>
          <Icon size={15} />
          <span class="nav-label">{section.label}</span>
          {#if sectionFlag[section.id]}
            <span
              class="flag"
              data-tone={sectionFlag[section.id]}
              title="Something in this section needs attention"
            ></span>
          {/if}
        </button>
      </li>
    {/each}
  </ul>

  <div class="foot">
    <button class="quiet" onclick={() => revealConfigDir()}>
      <Folder size={14} /> Open folder
    </button>
  </div>
</nav>

<style>
  nav {
    width: 240px;
    flex: none;
    display: flex;
    flex-direction: column;
    min-height: 0;
    border-right: 1px solid var(--border);
    background: var(--bg-raised);
    padding: var(--space-3) var(--space-2);
  }

  .brand {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    padding: var(--space-1) var(--space-2) var(--space-4);
    font-family: var(--font-display);
    font-size: var(--text-md);
    font-weight: var(--weight-semibold);
  }

  ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .nav-item {
    position: relative;
    width: 100%;
    display: flex;
    align-items: center;
    gap: var(--space-2);
    justify-content: flex-start;
    text-align: left;
    border: none;
    background: none;
    padding: var(--space-2) var(--space-2) var(--space-2) var(--space-3);
    border-radius: var(--radius-md);
    color: var(--text-dim);
  }

  .nav-item:hover:not(:disabled) {
    background: var(--bg-hover);
    border-color: transparent;
    color: var(--text);
  }

  .nav-item.active {
    background: var(--bg-hover);
    color: var(--text);
    font-weight: var(--weight-medium);
  }

  /* Decorative: the tint is what says "current". */
  .rail {
    position: absolute;
    left: 0;
    top: 6px;
    bottom: 6px;
    width: 2px;
    border-radius: var(--radius-pill);
    background: linear-gradient(var(--brand-from), var(--brand-to));
    opacity: 0;
    transition: opacity var(--dur-fast) var(--ease-out);
  }

  .nav-item.active .rail {
    opacity: 1;
  }

  .nav-label {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .flag {
    width: 6px;
    height: 6px;
    flex: none;
    border-radius: 50%;
  }

  .flag[data-tone="bad"] {
    background: var(--danger);
  }

  .flag[data-tone="warn"] {
    background: var(--warn);
  }

  .foot {
    margin-top: auto;
    padding-top: var(--space-2);
    border-top: 1px solid var(--border);
  }

  .foot button {
    width: 100%;
    justify-content: flex-start;
  }
</style>

// src/settings/SettingsNav.tsx
// One entry per section, Actions included — a single "Actions" item, not one per
// file: the list belongs in the pane, where a row has room for its Input Source
// and its hotkey. A nav column of Actions would make "pick a section" and "pick
// an Action" the same gesture for two unlike things.
import {
  FolderIcon,
  KeyboardIcon,
  ListIcon,
  PaletteIcon,
  PlugIcon,
  SlidersIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { BrandMark } from "@/components/BrandMark";
import { revealConfigDir } from "@/lib/ipc";
import { useStore } from "@/lib/useStore";
import { actionStore } from "./actions";
import { settings, type SectionRoute } from "./store";

const SECTIONS: { id: SectionRoute; label: string; icon: typeof PlugIcon }[] = [
  { id: "connection", label: "Connection", icon: PlugIcon },
  { id: "actions", label: "Actions", icon: ListIcon },
  { id: "triggering", label: "Triggering", icon: KeyboardIcon },
  { id: "appearance", label: "Appearance", icon: PaletteIcon },
  { id: "defaults", label: "Model defaults", icon: SlidersIcon },
];

export function SettingsNav() {
  const store = useStore(settings);
  const actions = useStore(actionStore);

  /** A section is flagged when something inside it needs attention, so a
   *  problem in a pane you are not looking at is still discoverable. A degraded
   *  model list is the warning colour, not red: the dropdown still works. */
  const flags: Record<SectionRoute, "bad" | "warn" | null> = {
    connection:
      store.keyStatus?.kind === "read-error" || store.test.state === "failed"
        ? "bad"
        : store.keyStatus?.kind === "no-credential"
          ? "warn"
          : null,
    // A file that does not parse, or a Direct Hotkey that lost its conflict:
    // both are only repairable from inside this section.
    actions: actions.flagged ? "bad" : null,
    triggering: store.startupErrors.length > 0 ? "bad" : null,
    appearance: null,
    defaults: store.models !== null && !store.models.live ? "warn" : null,
  };

  return (
    <nav
      aria-label="Settings"
      className="bg-sidebar flex w-52 min-h-0 flex-none flex-col border-r px-2.5 py-3.5"
    >
      <div className="font-display flex items-center gap-2 px-2 pt-0.5 pb-4.5 text-sm font-semibold">
        {/* The one chromatic thing in the window, and the reason `--brand` is a
            token of its own: everything else here is ink on paper. */}
        <BrandMark className="text-brand size-4.25" />
        <span>Beckon</span>
      </div>

      <ul className="flex list-none flex-col gap-0.5 p-0">
        {SECTIONS.map((section) => {
          const Icon = section.icon;
          const active = store.route === section.id;
          return (
            <li key={section.id}>
              <button
                type="button"
                aria-current={active ? "page" : undefined}
                onClick={() => store.go(section.id)}
                className={[
                  "flex w-full items-center justify-start gap-2.25 rounded-md px-2.25 py-1.5 text-left",
                  "focus-visible:ring-ring/50 focus-visible:ring-[3px] focus-visible:outline-none",
                  // The fill arrives rather than appearing. One frame is what
                  // makes a nav column feel like a set of radio buttons; 150ms
                  // is short enough that it never delays the pane behind it,
                  // which swaps on the same curve.
                  "transition-colors duration-150 ease-out motion-reduce:transition-none",
                  // Inversion is the marker: the current row is the only filled
                  // thing in the window, so it needs no rail and no weight
                  // change beside it. The hover tint is then free to mean
                  // "under the pointer" and nothing else.
                  active
                    ? "bg-primary text-primary-foreground font-medium"
                    : "text-muted-foreground hover:bg-accent hover:text-accent-foreground",
                ].join(" ")}
              >
                {/* The icon inherits the row's colour, and an inherited change
                    only animates where the child declares the transition too —
                    without this the label eases and the glyph snaps. */}
                <Icon className="size-3.75 flex-none transition-colors duration-150 ease-out motion-reduce:transition-none" />
                <span className="min-w-0 flex-1 truncate">{section.label}</span>
                {/* Not drawn on the current row. A 6px dot on the inverted fill
                    is 2.7:1 at best and 1.3:1 for the warning tone — and it is
                    the one row whose problem is already on screen, in the pane
                    to the right. */}
                {flags[section.id] && !active ? (
                  <span
                    title="Something in this section needs attention"
                    className={`size-1.5 flex-none rounded-full ${
                      flags[section.id] === "bad" ? "bg-destructive" : "bg-warning"
                    }`}
                  />
                ) : null}
              </button>
            </li>
          );
        })}
      </ul>

      <div className="mt-auto border-t pt-2">
        <Button
          variant="ghost"
          className="w-full justify-start"
          onClick={() => void revealConfigDir()}
        >
          <FolderIcon className="size-3.5" /> Open folder
        </Button>
      </div>
    </nav>
  );
}
